# Generated by Django 5.1.4 on 2026-05-22 11:58

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodDonorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pillar', models.CharField(choices=[('blood', 'Blood Donation'), ('medical_bills', 'Medical Bill Payment'), ('food', 'Surplus Food')], max_length=20)),
                ('role', models.CharField(max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('admin_message', models.TextField(blank=True)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('phone', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=100)),
                ('display_name', models.CharField(max_length=150)),
                ('notes', models.TextField(blank=True)),
                ('blood_type', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3)),
                ('last_donation_date', models.DateField(blank=True, null=True)),
                ('availability_notes', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blood_donor_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'pillar', 'role')},
            },
        ),
        migrations.CreateModel(
            name='BloodRequesterProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pillar', models.CharField(choices=[('blood', 'Blood Donation'), ('medical_bills', 'Medical Bill Payment'), ('food', 'Surplus Food')], max_length=20)),
                ('role', models.CharField(max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('admin_message', models.TextField(blank=True)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('phone', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=100)),
                ('display_name', models.CharField(max_length=150)),
                ('notes', models.TextField(blank=True)),
                ('blood_type', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3)),
                ('urgency', models.CharField(choices=[('routine', 'Routine'), ('urgent', 'Urgent'), ('critical', 'Critical')], default='routine', max_length=20)),
                ('medical_context', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blood_requester_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'pillar', 'role')},
            },
        ),
        migrations.CreateModel(
            name='CharityMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('body', models.TextField(max_length=2000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charity_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='FoodDistributorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pillar', models.CharField(choices=[('blood', 'Blood Donation'), ('medical_bills', 'Medical Bill Payment'), ('food', 'Surplus Food')], max_length=20)),
                ('role', models.CharField(max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('admin_message', models.TextField(blank=True)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('phone', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=100)),
                ('display_name', models.CharField(max_length=150)),
                ('notes', models.TextField(blank=True)),
                ('org_name', models.CharField(max_length=200)),
                ('org_type', models.CharField(choices=[('hospital', 'Hospital'), ('volunteer', 'Volunteer Group'), ('ngo', 'NGO'), ('other', 'Other')], max_length=20)),
                ('service_area', models.CharField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_distributor_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'pillar', 'role')},
            },
        ),
        migrations.CreateModel(
            name='FoodSupplierProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pillar', models.CharField(choices=[('blood', 'Blood Donation'), ('medical_bills', 'Medical Bill Payment'), ('food', 'Surplus Food')], max_length=20)),
                ('role', models.CharField(max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('admin_message', models.TextField(blank=True)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('phone', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=100)),
                ('display_name', models.CharField(max_length=150)),
                ('notes', models.TextField(blank=True)),
                ('business_name', models.CharField(max_length=200)),
                ('business_type', models.CharField(choices=[('hotel', 'Hotel'), ('restaurant', 'Restaurant'), ('catering', 'Catering'), ('other', 'Other')], max_length=20)),
                ('pickup_address', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_supplier_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'pillar', 'role')},
            },
        ),
        migrations.CreateModel(
            name='MedicalRecipientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pillar', models.CharField(choices=[('blood', 'Blood Donation'), ('medical_bills', 'Medical Bill Payment'), ('food', 'Surplus Food')], max_length=20)),
                ('role', models.CharField(max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('admin_message', models.TextField(blank=True)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('phone', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=100)),
                ('display_name', models.CharField(max_length=150)),
                ('notes', models.TextField(blank=True)),
                ('patient_name', models.CharField(max_length=150)),
                ('hospital_name', models.CharField(max_length=200)),
                ('bill_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(1)])),
                ('bill_reference', models.CharField(max_length=100)),
                ('bill_document', models.FileField(blank=True, upload_to='medical_bills/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png'])])),
                ('condition_summary', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_recipient_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'pillar', 'role')},
            },
        ),
        migrations.CreateModel(
            name='MedicalSponsorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pillar', models.CharField(choices=[('blood', 'Blood Donation'), ('medical_bills', 'Medical Bill Payment'), ('food', 'Surplus Food')], max_length=20)),
                ('role', models.CharField(max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('admin_message', models.TextField(blank=True)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('phone', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=100)),
                ('display_name', models.CharField(max_length=150)),
                ('notes', models.TextField(blank=True)),
                ('max_pledge_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('sponsor_notes', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_sponsor_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'pillar', 'role')},
            },
        ),
        migrations.CreateModel(
            name='SurplusListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_description', models.TextField()),
                ('quantity', models.CharField(max_length=100)),
                ('available_until', models.DateTimeField()),
                ('pickup_window', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('active', 'Active'), ('claimed', 'Claimed'), ('expired', 'Expired')], default='active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='charity.foodsupplierprofile')),
            ],
        ),
        migrations.CreateModel(
            name='BloodMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intro_message', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=10)),
                ('requester_accepted', models.BooleanField(default=True)),
                ('donor_accepted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='charity.blooddonorprofile')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='charity.bloodrequesterprofile')),
            ],
            options={
                'unique_together': {('donor', 'requester')},
            },
        ),
        migrations.CreateModel(
            name='MedicalMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_message', models.TextField()),
                ('pledge_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=10)),
                ('recipient_accepted', models.BooleanField(default=False)),
                ('sponsor_accepted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='charity.medicalrecipientprofile')),
                ('sponsor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='charity.medicalsponsorprofile')),
            ],
            options={
                'unique_together': {('recipient', 'sponsor')},
            },
        ),
        migrations.CreateModel(
            name='FoodPickupRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=10)),
                ('distributor_accepted', models.BooleanField(default=True)),
                ('supplier_accepted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('distributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickup_requests', to='charity.fooddistributorprofile')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickup_requests', to='charity.surpluslisting')),
            ],
            options={
                'unique_together': {('listing', 'distributor')},
            },
        ),
    ]
