# Generated by Django 5.2.6 on 2026-02-05 07:42

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_customuser_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='firstname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='lastname',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='donorapplication',
            old_name='reason',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='address',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='status',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='user_type',
        ),
        migrations.RemoveField(
            model_name='donorapplication',
            name='donor_type',
        ),
        migrations.RemoveField(
            model_name='donorapplication',
            name='photo',
        ),
        migrations.AddField(
            model_name='customuser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='charityapplication',
            name='charity_category',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='charityapplication',
            name='user',
            field=models.OneToOneField(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, related_name='charity_application', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='donorapplication',
            name='charity_category',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='donorapplication',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='donor_application', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='donorrequest',
            name='charity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='app.charityapplication'),
        ),
        migrations.AlterField(
            model_name='donorrequest',
            name='donor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='app.donorapplication'),
        ),
    ]
