# Generated by Django 5.1.4 on 2025-05-02 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_customuser_options_alter_customuser_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.IntegerField(choices=[(1, 'Normal'), (2, 'Seller'), (3, 'Charity'), (4, 'Doctor')], default=1),
        ),
    ]
