# Generated by Django 5.2.6 on 2026-01-21 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_donorapplication_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donorapplication',
            name='charity_category',
            field=models.CharField(choices=[('health', 'Health'), ('food', 'Food'), ('education', 'Education'), ('money', 'Money'), ('clothes', 'Clothes'), ('other', 'Other')], default='other', max_length=20),
            preserve_default=False,
        ),
    ]
