# Generated by Django 5.2.6 on 2025-10-03 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_charityoption_charityrequest_charitydonor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donorapplication',
            name='message',
        ),
        migrations.RemoveField(
            model_name='donorapplication',
            name='user',
        ),
        migrations.AddField(
            model_name='donorapplication',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='donorapplication',
            name='donor_type',
            field=models.CharField(choices=[('Individual', 'Individual'), ('Organization', 'Organization')], default='Individual', max_length=20),
        ),
        migrations.AddField(
            model_name='donorapplication',
            name='email',
            field=models.EmailField(default='example@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='donorapplication',
            name='name',
            field=models.CharField(default='Default Name', max_length=200),
        ),
        migrations.AddField(
            model_name='donorapplication',
            name='phone',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='donorapplication',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='donor_photos/'),
        ),
        migrations.AddField(
            model_name='donorapplication',
            name='reason',
            field=models.TextField(blank=True),
        ),
    ]
