# Generated by Django 5.2.6 on 2025-10-05 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_donorapplication_message_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharityApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('description', models.TextField(help_text='Describe your charity purpose or mission')),
                ('photo', models.ImageField(upload_to='charity_photos/')),
                ('document', models.FileField(blank=True, null=True, upload_to='charity_documents/')),
                ('is_approved', models.BooleanField(default=False)),
            ],
        ),
    ]
