# Generated by Django 5.2.6 on 2025-10-18 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_charityapplication'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='charityapplication',
            name='description',
        ),
        migrations.RemoveField(
            model_name='charityapplication',
            name='document',
        ),
    ]
