# Generated by Django 5.2.6 on 2026-01-08 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_charityapplication_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donor_type', models.CharField(choices=[('personal', 'Personal'), ('organization', 'Organization')], max_length=20)),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('photo', models.ImageField(upload_to='donor_photos/')),
                ('reason', models.TextField()),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
