# Generated by Django 5.2.6 on 2026-01-12 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_donor'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
